packages:
  - ./packages/*

catalog:
  '@sadan4/devtools-pretty-printer': 1.x
  '@types/node': 24.x
  ts-api-utils: 2.x
  typescript: 5.x
  vitest: 3.2.4

hoist: true

hoistWorkspacePackages: false

patchedDependencies:
  ts-api-utils: patches/ts-api-utils.patch
