packages:
  - ./packages/*

catalog:
  '@sadan4/devtools-pretty-printer': ^1.0.4
  '@types/node': ^24.6.0
  ts-api-utils: ^2.1.0
  typescript: ^5.0.0
  vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild

patchedDependencies:
  ts-api-utils: patches/ts-api-utils.patch
